keys:
  - &age_aanar age1hfnm8kxc85kp26g5hhy7z0garc8dq9z7wr24ylkxyty9mtrdkq2sr6e3ku
  # - &age_0commitment todo
creation_rules:
  - path_regex: aanar/secrets/[^/]+$
    key_groups:
    - age:
      - *age_aanar
  # - path_regex: 0commitment/secrets/[^/]+$
  #   key_groups:
  #   - age:
  #     - *age_0commitment