creation_rules:
  - path_regex: aanar/secrets/[^/]+$
    key_groups:
    - pgp:
      - DC31 32DC 45CF 60E4 43D2  C073 8A9C E13B 5936 6434
  - path_regex: 0commitment/secrets/[^/]+$
    key_groups:
    - pgp:
      - DC31 32DC 45CF 60E4 43D2  C073 8A9C E13B 5936 6434